version: "3"

services:
  mock_gateway:
    image: python_env
    container_name: lambda-mock-gateway
    volumes:
      - .:/code
    environment:
      - FLASK_APP=lambda_gateway
    command: sh util/docker/entrypoint.sh
    ports:
      - "5555:5555"
    depends_on:
      - api_destination
      - fake_s3

  fake_s3:
    image: localstack/localstack:latest
    container_name: lambda-fake-s3
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=fake_s3
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./util/init_s3.sh:/docker-entrypoint-initaws.d/init_s3.sh
      - ./test/fixtures:/tmp/localstack/fixtures
    ports:
      - "4563-4599:4563-4599"

  api_destination:
    image: python_env
    container_name: lambda-destination-app
    volumes:
      - .:/code
    environment:
      - FLASK_APP=api_destination
    command: python src/mock_services/api_destination.py
    ports:
      - "5005:5005"
  
  test_app:
    image: python_env
    volumes:
      - .:/code
    command: pytest test/
