AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Amperity supported Lambda logic for handling data out of our webhook destination.
Resources:
  ManagedInstanceRolec31818:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ManagedInstanceRolec31818
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: PinpointFullAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - mobiletargeting:*
            Resource: '*'
    Metadata:
      SamResourceId: ManagedInstanceRolec31818
  AmperityRunnerGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: AmperityRunnerGatewayAuthorization
    Metadata:
      SamResourceId: AmperityRunnerGateway
  AmperityRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: amperity-amazon-pinpoint-runner-c31818
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 2541d230-ece3-45bc-af2e-9aee69f0e5da
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 900
      Role:
        Fn::GetAtt:
        - ManagedInstanceRolec31818
        - Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: AmperityRunnerGateway
            Path: /run
            Method: post
      Policies:
      - LambdaInvokePolicy:
          FunctionName: amperity-amazon-pinpoint-runner-c31818
      Environment:
        Variables:
          PINPOINT_APP_ID: ''
          PINPOINT_ORIGINATION_NUMBER: ''
    Metadata:
      SamResourceId: AmperityRunnerFunction
Outputs:
  AmperityRunnerFunctionAPI:
    Description: 'API Gateway endpoint URL for FunctionName: amperity-amazon-pinpoint-runner-c31818'
    Value:
      Fn::Sub: https://${AmperityRunnerGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/run/
  AmperityRunnerFunctionAPIKey:
    Description: 'API Gateway API Key for FunctionName: amperity-amazon-pinpoint-runner-c31818'
    Value:
      Fn::Sub: https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/${AmperityRunnerGatewayApiKey}