AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Amperity supported Lambda logic for handling data out of our webhook destination.
Resources:
  ManagedInstanceRole7db6af:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ManagedInstanceRole7db6af
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      - arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    Metadata:
      SamResourceId: ManagedInstanceRole7db6af
  AmperityRunnerGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: AmperityRunnerGatewayAuthorization
    Metadata:
      SamResourceId: AmperityRunnerGateway
  AmperityRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: amperity-amazon-redshift-runner-7db6af
      CodeUri:
        Bucket: <%REPO_BUCKET%>
        Key: 4f925ef7-e485-495d-b0e0-9156f8fa57cd
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 900
      Role:
        Fn::GetAtt:
        - ManagedInstanceRole7db6af
        - Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: AmperityRunnerGateway
            Path: /run
            Method: post
      Policies:
      - LambdaInvokePolicy:
          FunctionName: amperity-amazon-redshift-runner-7db6af
      Environment:
        Variables:
          REDSHIFT_CLUSTER_ID: ''
          REDSHIFT_DB_NAME: ''
          REDSHIFT_DB_USER: ''
          REDSHIFT_IAM_ROLE: ''
          REDSHIFT_TABLE_NAME: ''
          S3_BUCKET: ''
    Metadata:
      SamResourceId: AmperityRunnerFunction
Outputs:
  AmperityRunnerFunctionAPI:
    Description: 'API Gateway endpoint URL for FunctionName: amperity-amazon-redshift-runner-7db6af'
    Value:
      Fn::Sub: https://${AmperityRunnerGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/run/
  AmperityRunnerFunctionAPIKey:
    Description: 'API Gateway API Key for FunctionName: amperity-amazon-redshift-runner-7db6af'
    Value:
      Fn::Sub: https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/api-keys/${AmperityRunnerGatewayApiKey}